version: '3.9'

services:
  apigateway:
    build:
      context: ./src/ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - questionservice
      - answercheckservice
      - examgeneratorservice
      - questionupdateservice
    networks:
      - quiz-network

  questionservice:
    build:
      context: ./src/QuestionService
    networks:
      - quiz-network

  answercheckservice:
    build:
      context: ./src/AnswerCheckService
    networks:
      - quiz-network

  examgeneratorservice:
    build:
      context: ./src/ExamGeneratorService
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge